[package]
name = "fedora"
description = "base library for interacting with fedora services"
license = "MIT OR Apache-2.0"

version = "0.0.6"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = ["api-bindings"]
keywords = ["fedora", "client", "authentication", "openid"]
repository = "https://github.com/ironthree/fedora-rs"

[features]
default = []
debug = []

[dependencies]
cookie = "^0.12.0"
failure = "^0.1"
reqwest = "^0.9"
serde = { version = "^1.0.103", features = ["derive"] }
serde_json = "^1.0.44"
