[package]
name = "fedora"
description = "base library for interacting with fedora services"
license = "MIT OR Apache-2.0"

version = "0.2.1"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = ["api-bindings"]
keywords = ["fedora", "client", "authentication", "openid"]
repository = "https://github.com/ironthree/fedora-rs"

[features]
default = []
debug = []

[dependencies]
failure = "^0.1.6"
reqwest = { version = "^0.10.0", features = ["blocking", "cookies"] }
serde = { version = "^1.0.104", features = ["derive"] }
serde_json = "^1.0.44"
url = "^2.1.0"
